apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: opc-ecosystem-images
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opc-ecosystem-images
    app.kubernetes.io/part-of: ecosystem-images
  name: opc-ecosystem-images
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: opc-ecosystem-images
status:
  loadBalancer: {}
